export type SignInErrorErrorCode =
  | "SIGN_IN_USER_NOT_FOUND"
  | "SIGN_IN_INVALID_CREDENTIALS"
  | "SIGN_IN_HASH_ERROR"
  | "SIGN_IN_INVALID_PASSWORD"
  | "SIGN_IN_GENERATE_TOKEN_ERROR"
  | "SIGN_IN_PERSISTENCE_ERROR";
