export type HashError = 'HASH_RANDOM_BYTES_FAILED' | 'HASH_DERIVE_KEY_FAILED';

export type VerifyHashError =
  | 'VERIFY_HASH_INVALID_FORMAT'
  | 'VERIFY_HASH_UNSUPPORTED_ALGORITHM'
  | 'VERIFY_HASH_INVALID_PARAMS'
  | 'VERIFY_HASH_INVALID_BASE64'
  | 'VERIFY_HASH_INVALID_SALT_LENGTH'
  | 'VERIFY_HASH_INVALID_KEY_LENGTH'
  | 'VERIFY_HASH_DERIVE_KEY_FAILED'
  | 'VERIFY_HASH_COMPARISON_FAILED';
